openapi: 3.0.0
info:
  version: 1.0.0
  title: Test api for project
  description: This api is a test version to connect the backend and frontend

components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: http
      scheme: bearer       # can be "header", "query" or "cookie"
      bearerFormat: JWT  # name of the header, query parameter or cookie
  
servers: 
  - url: https://app.insertname.com/api
paths: 
  /accounts/{accountID}:
    get:
      security: 
        - ApiKeyAuth: []
      operationId: GetAccountByID
      description: Returns an account by ID
      parameters: 
      - name: accountID
        in: path
        required: true
        description: The ID of the account to return (UUID)
        schema:
          type: string
          title: schema_get_account_id
          description: schema to get the account
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
        example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: get_account_id_response
                type: object
                description: response to provide account details
                required: 
                - ID
                - Name
                - Email
                properties:
                  ID:
                    type: string
                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                    description: The id of the account
                  Name:
                    type: string
                    description: the name of the account
                  Email:
                    type: string
                    description: the email address of the account
              example:
                { ID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a1, Name: Mark Wijnbergen, Email: markwijnbergen@hey.com }      
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
    delete:
      security: 
          - ApiKeyAuth: []
      operationId: DeleteAccountByID
      description: Delete the account with this ID
      parameters: 
      - name: accountID
        in: path
        required: true
        description: The ID of the account to return (UUID)
        schema:
          type: string
          title: delete_account_id
          description: schema to delete the account with a specific id
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a1
      responses:
        '200':
          description: OK
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /accounts/{accountID}/projects:
    get:
      security: 
        - ApiKeyAuth: []
      operationId: GetProjectsOfAccount
      description: returns all projects where this account is involved in 
      parameters: 
      - name: accountID
        in: path
        required: true
        description: The ID of the account
        schema:
          type: string
          title: schema_projects_account_id
          description: the schema to fetch the projects of a specific account
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: projects_account_id
                description: response with the projects of a specific account
                type: object
                properties:
                  projects:
                    type: array
                    title: projects
                    description: an array with all projects
                    items:
                      type: object
                      title: project
                      description: a project object
                      properties:
                        projectID:
                          type: string
                          description: the id of a project
                          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        projectName:
                          type: string
                          description: the name of a project
              example:
                {projects: [{projectID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a1, projectName: project 1}, {projectID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2, projectName: project 2}]}
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /authentication/login:
    post:
      operationId: LogInWithAccount
      description: logging in the account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: login_account
              type: object
              required: 
                - grantType
                - emailAddress
              properties:
                grantType:
                  type: string
                  enum: [password, autenthicationToken]
                  description: type of grant type to log in with
                emailAddress:
                  type: string
                  description: account email address to log in with
                password:
                  type: string
                  description: password of the account to log in with
                accessToken:
                  type: string
                  description: accesstoken of the account to log in with
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            examples:
              password:
                value:
                  grantType: password
                  emailAddress: markwijnbergen@hey.com
                  password: password 
              token:
                value:
                  grantType: accessToken
                  emailAddress: markwijnbergen@hey.com
                  accessToken: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: Account details
                description: the account details provided when the user logs in as a JWT token
                type: object
                required: 
                  - accountID
                  - accessToken
                  - refreshToken
                properties:
                  accountID:
                    type: string
                    description: The account id.
                  accessToken:
                    type: string
                    description: The access token.
                  refreshToken:
                    type: string
                    description: The refresh token.
              example: 
                {
                  accountID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2,
                  accessToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik1hcmsgV2lqbmJlcmdlbiIsImFjY2Vzc3Rva2VuIjoxNTE2MjM5MDIyLCJyZWZyZXNodG9rZW4iOjc1Mzk3NTM1N30.V1JMLTr7R_yPdkbpZQ9kpUmmmq8cyEbpNRk5B78fpYw,
                  refreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik1hcmsgV2lqbmJlcmdlbiIsImFjY2Vzc3Rva2VuIjoxNTE2MjM5MDIyLCJyZWZyZXNodG9rZW4iOjc1Mzk3NTM1N30.V1JMLTr7R_yPdkbpZQ9kpUmmmq8cyEbpNRk5B78fpYw
                }
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /authentication/refresh:
    post:
      operationId: RefreshAccessToken
      description: Refresh the access token of the account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: Refresh details
              description: Details necessary to refresh the access token
              type: object
              required: 
                - accountID
                - refreshToken
              properties:
                accountID:
                  type: string
                  description: The account ID.
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                refreshToken:
                  type: string
                  description: the refreshToken used to update the acces token
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            example: 
              password:
                value:
                  grantType: password
                  emailAddress: markwijnbergen@hey.com
                  password: password 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: JWT account details
                description: the account details provided when the user logs in as a JWT token
                type: object
                required: 
                  - JWT
                properties:
                  JWT:
                    type: string
                    description: The jwt token with all information.
              example: 
                {JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SUQiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik1hcmsgV2lqbmJlcmdlbiIsImFjY2Vzc3Rva2VuIjoxNTE2MjM5MDIyLCJyZWZyZXNodG9rZW4iOjc1Mzk3NTM1N30.V1JMLTr7R_yPdkbpZQ9kpUmmmq8cyEbpNRk5B78fpYw}    
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /authentication/revoke:
    post:
      security: 
        - ApiKeyAuth: []
      operationId: LogOutWithAccount
      description: logging out the account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: logout_account
              description: schema to revoke access with the specific account
              type: object
              required: 
                - accessToken
              properties:
                accessToken:
                  type: string
                  description: access token that needs to be revoked to log out
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            example: 
              {accessToken: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2}
      responses:
        '200':
          description: OK
  /projects/{projectID}/{accountID}/tests:
    get:
      security: 
        - ApiKeyAuth: []
      operationId: GetTestsToPerformByAccount
      description: Get all tests that need to be performed by account
      parameters: 
      - name: projectID
        in: path
        required: true
        description: The ID of the project to return (UUID)
        schema:
          title: project_id
          description: the id of the project to get the tests from
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      - name: accountID
        in: path
        required: true
        description: The ID of the account to return (UUID)
        schema:
          title: account_id
          description: the id of the account to get the tests from
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: tests_project
                description: tests that the account needs to perform for this specific project
                type: object
                properties:
                  testsToPerform:
                    type: array
                    title: tests
                    description: array of tests
                    items:
                      type: object
                      title: test
                      description: test to perform
                      properties:
                        testID:
                          type: string
                          description: id of the test
                          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                        testName:
                          description: name of the test
                          type: string
                        testType:
                          type: string
                          enum: [generic, stroopDirection, stroopColor]
                          description: type of the test
              example:
                {testsToPerform:[{testID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2, testName: test 1}, {testID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a3, testName: test 2}]}
        '400':
          description: The specified project ID or account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /projects/{projectID}/genericTests/{testID}:
    get:
      security: 
        - ApiKeyAuth: []
      operationId: GetGenericTestOfProject
      description: Get a generic test with specific ID
      parameters: 
      - name: projectID
        in: path
        required: true
        description: The ID of the project to return
        schema:
          title: project_id
          description: schema of the project id
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      - name: testID
        in: path
        required: true
        description: The ID of the test to return
        schema:
          title: test_id
          description: schema of the test id
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: generic_test
                description: schema of a generic test
                required:
                  - title
                  - description
                  - displayAnswers
                  - finalRemark
                  - questions
                type: object
                properties:
                  title:
                    type: string
                    description: Title of questionnaire
                  description:
                    type: string
                    description: Description of questionnaire
                  displayAnswers:
                    type: boolean
                    description: To determine whether the answers should be displayed at the end of the questionnaire
                  finalRemark:
                    type: string
                    description: Final remakrs at the end of the questionnaire
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          title: question
                          type: string
                        questionType:
                          type: string
                          enum: [openQuestion, multipleChoice, slider]
                        answers:
                          type: array
                          items:
                            type: string
              example:
                {title: Title of Questionnaire, description: Hi thanks for joining, displayAnswers: true, finalRemark: Thanks for your participation, questions: [{question: whats your age, questionType: openQuestion, answers: {}}, {question: whats your sex, questionType: multipleChoice, answers: [male, female]}, {question: rate your happines, questionType: slider, answers: [very unhappy, unhappy, moderate, happy, very happy]} ]}
        '400':
          description: The specified project ID or test ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
    post:
      security: 
        - ApiKeyAuth: []
      operationId: SubmitAnswerToTest
      description: Submit the answer to the specific 
      parameters: 
      - name: projectID
        in: path
        required: true
        description: The ID of the project to return
        schema:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      - name: testID
        in: path
        required: true
        description: The ID of the test to return (UUID)
        schema:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
          example: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2
      requestBody:
        required: true
        content:
            application/json:
              schema:
                title: genericTestAnswers
                type: object
                description: The answers to a generic test
                properties:
                  accountID:
                    type: string
                    title: accountID
                    description: the id of the account that performed this test
                    pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                  answers:
                    title: array of answers
                    description: the array of answers for this questionnaire
                    type: array
                    items:
                      type: object
                      title: answer to question
                      description: the answer to a question
                      properties:
                        question:
                          type: integer
                          title: question number
                          description: the question number
                        answer:
                          type: string
                          title: answer to question
                          description: an answer to a question
                        timeToAnswer:
                          type: number
                          title: time to answer
                          description: the time in milliseconds to answer the question
              example:
                {accountID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2, answers: [{question: 1, answer: yo mama is so fat, timeToAnswer: 5000}, {question: 2, answer: They are taking the hobbits to Isengard, timeToAnswer: 3999}] }
      responses:
        '200':
          description: OK
        '400':
          description: The specified project ID or test ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /signup:
    post:
      security: 
        - ApiKeyAuth: []
      operationId: SendEmailForSignUp
      description: Sends an email address that needs to be signed up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: sign up
              description: schema for signing up
              type: object
              required:
                - senderAccountID
                - emailAddress
              properties:
                senderAccountID:
                  type: string
                  title: sender account id
                  description: account id of the account that invites the new user
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                emailAddress:
                  title: emailAddress
                  description: the email address of the newly invited person
                  type: string
            example:
              {senderAccountID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2, emailAddress: markwijnbergen@heycom }
      responses:
        '200':
          description: OK
        '400':
          description: The specified account ID or email address is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found
  /signup/create:
    post:
      security: 
        - ApiKeyAuth: []
      operationId: CreateNewAccount
      description: Creates a new account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: account_creation
              description: the schema to create the new account
              type: object
              required: 
                - firstName
                - lastName
                - emailAddress
                - senderAccountID
              properties:
                firstName:
                  title: first name
                  description: first name of the new user
                  type: string
                lastName:
                  title: last name
                  description: last name of the new user
                  type: string
                senderAccountID:
                  title: sender account id
                  description: the id of the account that invited the new user
                  type: string
                  pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
                emailAddress:
                  type: string
            example:
              { firstName: Mark, lastName: Wijnbergen, emailAddress: markwijnbergen@hey.com, senderAccountID: 0a8ba9ad-a93d-4991-8c23-c178b09fe6a2 }
      responses:
        '200':
          description: OK
        '400':
          description: The specified account ID is invalid
        '401':
          description: Authentication failed
        '404':
          description: Account not found